/*
 * ConnectBot Terminal
 * Copyright 2025 Kenny Root
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.connectbot.terminal

/**
 * Flag constants for the Kitty keyboard protocol progressive enhancement modes.
 *
 * These flags are set by the application running in the terminal via
 * `CSI > flags u` and control which keyboard features are enabled.
 */
internal object KittyKeyboardFlags {
    /** Disambiguate escape codes: encode all keys unambiguously, including plain ASCII. */
    const val DISAMBIGUATE = 1

    /** Report event types (press, repeat, release). */
    const val REPORT_EVENTS = 2

    /** Report alternate keys (shifted key and base layout key). */
    const val REPORT_ALTERNATES = 4

    /** Report all keys as escape sequences, even plain text keys without modifiers. */
    const val REPORT_ALL_KEYS = 8

    /** Report the text generated by key events as a codepoint. */
    const val REPORT_TEXT = 16
}

/**
 * Encodes key events as CSI-u sequences per the Kitty keyboard protocol.
 *
 * The Kitty keyboard protocol provides unambiguous encoding of keyboard events
 * using CSI (Control Sequence Introducer) sequences terminated with 'u'. The
 * general format is:
 *
 * ```
 * CSI unicode-key-code [; [modifiers] [: event-type] [; text-as-codepoint]] u
 * ```
 *
 * This encoder converts key events described by Unicode codepoints and VTerm
 * modifier bitmasks into the appropriate CSI-u byte sequences.
 *
 * @see <a href="https://sw.kovidgoyal.net/kitty/keyboard-protocol/">Kitty Keyboard Protocol</a>
 */
internal class KittyKeyboardEncoder {

    /**
     * The type of keyboard event being reported.
     */
    enum class EventType {
        /** Key was pressed down. */
        PRESS,
        /** Key is being held and auto-repeating. */
        REPEAT,
        /** Key was released. */
        RELEASE
    }

    /**
     * Encode a key event as a CSI-u byte sequence.
     *
     * @param codepoint The Unicode codepoint of the key (e.g., 97 for 'a', 13 for Enter).
     * @param modifiers VTerm modifier bitmask (bit 0 = Shift, bit 1 = Alt, bit 2 = Ctrl).
     * @param eventType The type of key event (press, repeat, or release).
     * @param flags The active Kitty keyboard flags set by the application.
     * @param shiftedKey The shifted version of the key codepoint (used with REPORT_ALTERNATES flag).
     * @param baseLayout The base layout key codepoint (used with REPORT_ALTERNATES flag).
     * @return The encoded CSI-u byte sequence, or null if the key should not be encoded
     *         (e.g., a simple ASCII key press with no flags requiring encoding).
     */
    fun encode(
        codepoint: Int,
        modifiers: Int,
        eventType: EventType,
        flags: Int,
        shiftedKey: Int = 0,
        baseLayout: Int = 0
    ): ByteArray? {
        // Determine if we need to encode this key at all
        if (!shouldEncode(codepoint, modifiers, eventType, flags)) {
            return null
        }

        // Convert VTerm modifiers to CSI-u modifiers: CSI-u mod = 1 + vtermMod
        val csiModifier = if (modifiers != 0) 1 + modifiers else 0

        // Map event type to protocol value: 1=press, 2=repeat, 3=release
        val eventTypeValue = when (eventType) {
            EventType.PRESS -> 1
            EventType.REPEAT -> 2
            EventType.RELEASE -> 3
        }

        // Determine which optional parts to include
        val reportEvents = flags and KittyKeyboardFlags.REPORT_EVENTS != 0
        val reportAlternates = flags and KittyKeyboardFlags.REPORT_ALTERNATES != 0
        val reportText = flags and KittyKeyboardFlags.REPORT_TEXT != 0

        // Determine if we need the event type suffix
        val includeEventType = reportEvents && eventType != EventType.PRESS

        // Map the codepoint to the appropriate key number for functional keys
        val keyNumber = mapToKeyNumber(codepoint)

        // Check if this is a functional key that uses a different CSI terminator
        val functionalMapping = getFunctionalKeyMapping(keyNumber)
        if (functionalMapping != null) {
            return encodeFunctionalKey(
                functionalMapping,
                csiModifier,
                eventTypeValue,
                includeEventType,
                reportAlternates,
                reportText,
                shiftedKey,
                baseLayout,
                codepoint
            )
        }

        // Build CSI-u sequence: CSI keyNumber [; [modifier[:event-type]] [; text]] u
        return buildCsiU(
            keyNumber,
            csiModifier,
            eventTypeValue,
            includeEventType,
            reportAlternates,
            reportText,
            shiftedKey,
            baseLayout
        )
    }

    /**
     * Determine if a key event should be encoded as a CSI-u sequence.
     */
    private fun shouldEncode(
        codepoint: Int,
        modifiers: Int,
        eventType: EventType,
        flags: Int
    ): Boolean {
        val disambiguate = flags and KittyKeyboardFlags.DISAMBIGUATE != 0
        val reportAllKeys = flags and KittyKeyboardFlags.REPORT_ALL_KEYS != 0
        val reportEvents = flags and KittyKeyboardFlags.REPORT_EVENTS != 0

        // If REPORT_ALL_KEYS is set, encode everything
        if (reportAllKeys) return true

        // If REPORT_EVENTS is set and this is not a press, encode it
        if (reportEvents && eventType != EventType.PRESS) return true

        // If DISAMBIGUATE is set, encode all keys
        if (disambiguate) return true

        // If there are modifiers beyond just the key itself, encode
        if (modifiers != 0) return true

        // No flags require encoding for this simple key press
        return false
    }

    /**
     * Map a codepoint to the key number used in the CSI-u sequence.
     * Most keys use their Unicode codepoint directly. Special/functional
     * keys are mapped to their protocol-defined numbers.
     */
    private fun mapToKeyNumber(codepoint: Int): Int {
        return when (codepoint) {
            VTermKey.ENTER -> 13
            VTermKey.TAB -> 9
            VTermKey.BACKSPACE -> 127
            VTermKey.ESCAPE -> 27
            VTermKey.INS -> 2
            VTermKey.DEL -> 3
            VTermKey.HOME -> 1
            VTermKey.END -> 4
            VTermKey.PAGEUP -> 5
            VTermKey.PAGEDOWN -> 6
            VTermKey.UP -> 0x41     // 'A'
            VTermKey.DOWN -> 0x42   // 'B'
            VTermKey.LEFT -> 0x44   // 'D'
            VTermKey.RIGHT -> 0x43  // 'C'
            in VTermKey.FUNCTION_0..VTermKey.FUNCTION_12 -> {
                mapFunctionKeyNumber(codepoint)
            }
            in VTermKey.KP_0..VTermKey.KP_EQUAL -> {
                mapKeypadKeyNumber(codepoint)
            }
            else -> codepoint
        }
    }

    /**
     * Map function key VTerm codes to their Kitty protocol key numbers.
     * In the Kitty protocol, function keys use specific CSI number sequences.
     */
    private fun mapFunctionKeyNumber(vtermKey: Int): Int {
        val fNum = vtermKey - VTermKey.FUNCTION_0
        return when (fNum) {
            1 -> 11    // F1 -> CSI 11 ~  or  CSI P
            2 -> 12    // F2 -> CSI 12 ~  or  CSI Q
            3 -> 13    // F3 -> CSI 13 ~  or  CSI R
            4 -> 14    // F4 -> CSI 14 ~  or  CSI S
            5 -> 15    // F5 -> CSI 15 ~
            6 -> 17    // F6 -> CSI 17 ~
            7 -> 18    // F7 -> CSI 18 ~
            8 -> 19    // F8 -> CSI 19 ~
            9 -> 20    // F9 -> CSI 20 ~
            10 -> 21   // F10 -> CSI 21 ~
            11 -> 23   // F11 -> CSI 23 ~
            12 -> 24   // F12 -> CSI 24 ~
            else -> 11 + fNum - 1
        }
    }

    /**
     * Map keypad VTerm codes to their Kitty protocol key numbers.
     * Keypad keys use codepoints in the 57399-57413 range.
     */
    private fun mapKeypadKeyNumber(vtermKey: Int): Int {
        return when (vtermKey) {
            VTermKey.KP_0 -> 57399
            VTermKey.KP_1 -> 57400
            VTermKey.KP_2 -> 57401
            VTermKey.KP_3 -> 57402
            VTermKey.KP_4 -> 57403
            VTermKey.KP_5 -> 57404
            VTermKey.KP_6 -> 57405
            VTermKey.KP_7 -> 57406
            VTermKey.KP_8 -> 57407
            VTermKey.KP_9 -> 57408
            VTermKey.KP_PERIOD -> 57409
            VTermKey.KP_DIVIDE -> 57410
            VTermKey.KP_MULT -> 57411
            VTermKey.KP_MINUS -> 57412
            VTermKey.KP_PLUS -> 57413
            VTermKey.KP_ENTER -> 57414
            VTermKey.KP_EQUAL -> 57415
            VTermKey.KP_COMMA -> 57416
            else -> 57399
        }
    }

    /**
     * Represents a functional key that uses a CSI sequence with a specific terminator
     * character (not 'u'). These include arrow keys (A/B/C/D), Home (H), End (F),
     * function keys (P/Q/R/S), and tilde-terminated keys (~).
     */
    private data class FunctionalKeyMapping(
        /** The key number parameter in the CSI sequence. */
        val number: Int,
        /** The terminator character (e.g., '~', 'A', 'P', 'H'). */
        val terminator: Char,
        /** Whether the number should be omitted when there are no modifiers. */
        val omitNumberWhenSimple: Boolean = false
    )

    /**
     * Get the functional key mapping for keys that use CSI sequences with
     * terminators other than 'u'.
     */
    private fun getFunctionalKeyMapping(keyNumber: Int): FunctionalKeyMapping? {
        return when (keyNumber) {
            // Arrow keys: CSI [1;mod] A/B/C/D
            0x41 -> FunctionalKeyMapping(1, 'A', omitNumberWhenSimple = true)  // Up
            0x42 -> FunctionalKeyMapping(1, 'B', omitNumberWhenSimple = true)  // Down
            0x43 -> FunctionalKeyMapping(1, 'C', omitNumberWhenSimple = true)  // Right
            0x44 -> FunctionalKeyMapping(1, 'D', omitNumberWhenSimple = true)  // Left

            // Home/End: CSI [1;mod] H/F
            1 -> FunctionalKeyMapping(1, 'H', omitNumberWhenSimple = true)     // Home
            4 -> FunctionalKeyMapping(1, 'F', omitNumberWhenSimple = true)     // End

            // Editing keys: CSI number [;mod] ~
            2 -> FunctionalKeyMapping(2, '~')   // Insert
            3 -> FunctionalKeyMapping(3, '~')   // Delete
            5 -> FunctionalKeyMapping(5, '~')   // PageUp
            6 -> FunctionalKeyMapping(6, '~')   // PageDown

            // F1-F4: CSI [1;mod] P/Q/R/S
            11 -> FunctionalKeyMapping(1, 'P', omitNumberWhenSimple = true)    // F1
            12 -> FunctionalKeyMapping(1, 'Q', omitNumberWhenSimple = true)    // F2
            13 -> FunctionalKeyMapping(1, 'R', omitNumberWhenSimple = true)    // F3
            14 -> FunctionalKeyMapping(1, 'S', omitNumberWhenSimple = true)    // F4

            // F5-F12: CSI number [;mod] ~
            15 -> FunctionalKeyMapping(15, '~')  // F5
            17 -> FunctionalKeyMapping(17, '~')  // F6
            18 -> FunctionalKeyMapping(18, '~')  // F7
            19 -> FunctionalKeyMapping(19, '~')  // F8
            20 -> FunctionalKeyMapping(20, '~')  // F9
            21 -> FunctionalKeyMapping(21, '~')  // F10
            23 -> FunctionalKeyMapping(23, '~')  // F11
            24 -> FunctionalKeyMapping(24, '~')  // F12

            else -> null
        }
    }

    /**
     * Encode a functional key that uses a CSI sequence with a specific terminator.
     */
    private fun encodeFunctionalKey(
        mapping: FunctionalKeyMapping,
        csiModifier: Int,
        eventTypeValue: Int,
        includeEventType: Boolean,
        reportAlternates: Boolean,
        reportText: Boolean,
        shiftedKey: Int,
        baseLayout: Int,
        originalCodepoint: Int
    ): ByteArray {
        val sb = StringBuilder()
        sb.append("\u001b[")

        val hasModifier = csiModifier > 0
        val hasEventType = includeEventType

        if (mapping.omitNumberWhenSimple && !hasModifier && !hasEventType) {
            // Simple case: CSI <terminator>
            sb.append(mapping.terminator)
        } else {
            // Include the number
            sb.append(mapping.number)

            if (hasModifier || hasEventType) {
                sb.append(';')
                if (hasModifier) {
                    sb.append(csiModifier)
                } else {
                    sb.append('1')
                }
                if (hasEventType) {
                    sb.append(':')
                    sb.append(eventTypeValue)
                }
            }

            sb.append(mapping.terminator)
        }

        return sb.toString().toByteArray(Charsets.US_ASCII)
    }

    /**
     * Build a CSI-u sequence for a non-functional key.
     *
     * Format: CSI keyNumber [; [modifier[:event-type]] [; shifted:base]] u
     */
    private fun buildCsiU(
        keyNumber: Int,
        csiModifier: Int,
        eventTypeValue: Int,
        includeEventType: Boolean,
        reportAlternates: Boolean,
        reportText: Boolean,
        shiftedKey: Int,
        baseLayout: Int
    ): ByteArray {
        val sb = StringBuilder()
        sb.append("\u001b[")
        sb.append(keyNumber)

        val hasModifier = csiModifier > 0
        val hasEventType = includeEventType
        val hasAlternates = reportAlternates && (shiftedKey > 0 || baseLayout > 0)
        val hasText = reportText && keyNumber in 32..0x10FFFF

        // Determine if we need the second parameter (modifiers section)
        if (hasModifier || hasEventType || hasAlternates || hasText) {
            sb.append(';')

            // Modifier value (default to 1 if we need the section but have no modifiers)
            val modValue = if (hasModifier) csiModifier else 1

            if (hasAlternates) {
                // Format: modifier:event-type:shifted:base
                sb.append(modValue)
                if (hasEventType) {
                    sb.append(':')
                    sb.append(eventTypeValue)
                }
                sb.append(':')
                if (shiftedKey > 0) {
                    sb.append(shiftedKey)
                }
                sb.append(':')
                if (baseLayout > 0) {
                    sb.append(baseLayout)
                }
            } else if (hasEventType) {
                sb.append(modValue)
                sb.append(':')
                sb.append(eventTypeValue)
            } else {
                sb.append(modValue)
            }

            // Text-as-codepoint section
            if (hasText) {
                sb.append(';')
                sb.append(keyNumber)
            }
        }

        sb.append('u')
        return sb.toString().toByteArray(Charsets.US_ASCII)
    }
}
